baseURL = "https://modest-neumann-b2f1a9.netlify.com/"
languageCode = "en-us"
title = "Orbville"
theme = "meghna-hugo"
defaultcontentlanguage = "en"

[params] # theme parameters
	author = "Omari R. Blackman"
	info = "Solutions Architect"
	description = "Orbville Solutions"
	
